In [1]:
import numpy as np
import pandas as pd

In [46]:
st = pd.read_csv('nombres.csv')
st['Proyecto'] = np.random.permutation(['mc-area', 'leave-one-out-estimator', 'grid-robot']*6 + ['mc-area'])
st

                              Nombre                 Proyecto
0   Benavides Lázaro  Mariela Liseth                  mc-area
1             Figueroa González Polo  leave-one-out-estimator
2        Lémus Flores Elmer Humberto  leave-one-out-estimator
3     Monterroso Zamora Ernesto René                  mc-area
4          Navas Solís Erwin Roberto               grid-robot
5        Orellana Alfaro Hugo Leonel               grid-robot
6   Santizo Flores  Allan Fernando *               grid-robot
7       Ajanel González Byron Rafael               grid-robot
8        Ávila Cabrera Helen Saraí *                  mc-area
9       De León Miranda José Domingo  leave-one-out-estimator
10        Gabriel Maselli David José  leave-one-out-estimator
11     Gordillo Sajbín Edgar Joaquin                  mc-area
12         Guzmán Sánchez Marianna *               grid-robot
13      Lemus Mackay Luis Fernando *                  mc-area
14       López Ortega María Fernanda                  mc-area
15      Ortiz Flores Andrés Miguel *  leave-one-out-estimator
16        Rodríguez Vásquez Marybeth  leave-one-out-estimator
17   Sánchez del Cid Diego Ignacio *                  mc-area
18  Santa María Rodas Pablo Andrés *               grid-robot